spring:
  h2:
    console:
      enabled: true
      path: /h2     # Context path
  datasource:
    url: jdbc:h2:mem:test     # JDBC URL
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력